Feature/add checks
NETWAYS/check_disk_btrfs pull request #8
Opened 2023-01-15 11:54 UTC by AdrienR

Hi,

Thank for your probe, but i also need to check raid array health, so their is my additions.

2023-01-16 07:39 UTC, martialblog commented
Hi, Thanks. I will take a look at it.

2023-01-16 08:08 UTC, martialblog requested changes
Looks good. Just some minor changes.

Thanks for writing tests!

2023-01-16 08:08 UTC, martialblog commented on check_disk_btrfs
> +        if is_device_missing is True:
This line can simply be `if is_device_missing:` the is True conditional is redundant. 

And there's some whitespaces in line 234 that can be removed

2023-01-16 08:08 UTC, martialblog commented on check_disk_btrfs
> +        if scrub_error:
Can we rename that function "has_scrub_error"? Then the condition reads nicer. Just a minor change.

2023-01-16 22:29 UTC, AdrienR commented on check_disk_btrfs
> +        if scrub_error:
Yep, it's done

2023-01-16 22:30 UTC, AdrienR commented on check_disk_btrfs
> +        if is_device_missing is True:
I think it's more readable by putting is True, so you know you are checking a bool, not a None or something

2023-01-17 09:01 UTC, martialblog commented on check_disk_btrfs
> +        if scrub_error:
Thanks

2023-01-17 09:07 UTC, martialblog commented
@AdrienR could you rebase the branch and resolve the conflicts? Then I will merge this

2023-01-17 09:17 UTC, AdrienR commented
> 

Thank, should be good now.

2023-01-17 09:19 UTC, merged